import "server-only";

import * as Sentry from "@sentry/nextjs";

import {getServerEnvironment} from "@/env/server";
import {getFirebaseAdminMessaging} from "@/lib/firebase/admin";
import {createAdminClient} from "@/lib/supabase/admin";

export async function deliverNotification(notificationId:string){const admin=createAdminClient();const {data:notification,error}=await admin.from("notifications").select("id,user_profile_id,channel,title,body,data,user_profiles(email,notification_preferences(email_enabled,push_enabled))").eq("id",notificationId).single();if(error||!notification)throw new Error("Notification not found");const user=notification.user_profiles as unknown as {email:string;notification_preferences:{email_enabled:boolean;push_enabled:boolean}|null};try{let providerMessageId:string|undefined;if(notification.channel==="email"){if(user.notification_preferences?.email_enabled!==false){const env=getServerEnvironment();const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({from:`FixMate Pakistan <${env.EMAIL_FROM_ADDRESS}>`,to:[user.email],subject:notification.title,text:notification.body}),signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error("Email provider rejected notification");const result=await response.json() as {id?:string};providerMessageId=result.id}}
if(notification.channel==="push"){if(user.notification_preferences?.push_enabled!==false){const {data:devices}=await admin.from("notification_devices").select("fcm_token").eq("user_profile_id",notification.user_profile_id).is("revoked_at",null);if(devices?.length){const result=await getFirebaseAdminMessaging().sendEachForMulticast({tokens:devices.map(device=>device.fcm_token),notification:{title:notification.title,body:notification.body},data:Object.fromEntries(Object.entries((notification.data??{}) as Record<string,unknown>).map(([key,value])=>[key,String(value)]))});providerMessageId=`${result.successCount}/${devices.length}`}}}
await admin.from("notifications").update({delivery_status:"sent",sent_at:new Date().toISOString(),provider_message_id:providerMessageId??null}).eq("id",notificationId);return true}catch(error){Sentry.captureException(error,{tags:{operation:"deliver_notification",channel:notification.channel}});await admin.from("notifications").update({delivery_status:"failed",failed_at:new Date().toISOString(),failure_reason:"Provider delivery failed"}).eq("id",notificationId);return false}}
