"use client";

import { CheckCircle2, LoaderCircle, Send } from "lucide-react";
import { useCallback, useState } from "react";

import { TurnstileWidget } from "@/components/security/turnstile-widget";
import { useRouter } from "@/i18n/navigation";
import type { ApiEnvelope } from "@/lib/api/response";

import { useApplication } from "./use-application";

export function ReviewStep(){const {data,error:loadError}=useApplication();const router=useRouter();const [token,setToken]=useState("");const [accepted,setAccepted]=useState(false);const [pending,setPending]=useState(false);const [error,setError]=useState("");const handleToken=useCallback((value:string)=>setToken(value),[]);if(!data)return <div className="panel-card">{loadError||"Preparing your application review…"}</div>;const app=data.application;const checks=[{label:"Personal and professional information",ready:Boolean(app.cnic_last4&&app.bio&&app.primary_city_id)},{label:`${data.services.length} selected services`,ready:data.services.length>0},{label:`${data.areas.length} service areas`,ready:data.areas.length>0},{label:`${data.schedules.length} availability windows`,ready:data.schedules.length>0},{label:`${data.documents.length} uploaded documents`,ready:data.documents.length>=4},{label:`${data.references.length} professional references`,ready:data.references.length>=2},{label:"Encrypted payout readiness",ready:Boolean(data.payout)}];async function submit(){setPending(true);setError("");const response=await fetch("/api/v1/professional/application/submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({declarationAccepted:accepted,turnstileToken:token})});const result=await response.json() as ApiEnvelope<{status:string}>;setPending(false);if(!result.success){setError(result.error.message);return}router.replace("/professional");router.refresh()}return <div className="review-layout"><section className="panel-card"><h2>Application readiness</h2><div className="readiness-list">{checks.map(item=><div className={item.ready?"is-ready":""} key={item.label}><CheckCircle2 size={18}/><span>{item.label}</span><strong>{item.ready?"Ready":"Needs attention"}</strong></div>)}</div></section><section className="panel-card declaration-card"><h2>Professional declaration</h2><p>I confirm that the information and documents I provided are accurate, I have permission to share reference details, and I agree to follow the FixMate Professional Code. I understand that submission does not guarantee approval or work.</p><label className="consent-check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I accept the professional applicant declaration.</span></label><TurnstileWidget action="professional_submit" onToken={handleToken}/>{error?<div className="form-alert form-alert--error">{error}</div>:null}<button className="button button--primary button--large auth-submit" onClick={submit} disabled={!accepted||!token||pending}>{pending?<LoaderCircle className="spin" size={18}/>:<Send size={18}/>} {pending?"Submitting securely…":"Submit for review"}</button></section></div>}
